### ISSUE TITLE
(s) tag not being removed when joining a match.

### ISSUE THREAD

**Issue by cgrahame** [Melodeiro/minqlx-plugins_mattiZed#5]
Hi, 

I have just setup a new QL server on a dedicated server running Ubuntu 16.04 LTS. It is running the latest version of your Queue plugin (ver 2.6.2).

For some reason, if I join the server and click join to enter the match it will leave the (s) tag in front of my name. eg (s)Bill instead of removing it and making it just Bill as it should be.

If I go back to spec and then rejoin again, it still has the (s) prepended to my name.

I have some other QL servers on a different server with the exact same configuration, but I do not get this issue on those servers with the queue plugin. Only difference is that that server is a VPS running UIbuntu 15.10 LTS.

I have checked the minqlx.log file and I see no errors there.

I have been pulling my hair out trying to figure out why the Queue plugin behaves like this on my new dedicated server and works fine on my VPS with the same exact QL configuration in the server start script.

Any help would be greatly appreciated.

**Comment by cgrahame** [comment]
Just an update. I have found that if I use the debugging command !qupd it will remove the (s) from in front of my name while in the match. Just can't figure out why the plugin doesn't correctly do this on its own when moving from spec to in the match.

If anyone can help with this issue I would greatly appreciate it.

**Comment by Melodeiro** [comment]
In order to use the queue plugin you should enable zmq:
`zmq_rcon_enable 1`
`zmq_rcon_password rconpassword`
`zmq_rcon_port rconport`
`zmq_stats_enable 1`
`zmq_stats_password statspassword`
`zmq_stats_port gameport`

**Comment by cgrahame** [comment]
Hi Melodeiro,

After reading your reply I was hoping it was something as simple as a misconfigured server variable. So with renewed hopes that it was something simple, I went and double checked those particular settings in the server start file and found they were all set correctly (I had copied the start file from my other working server). 

I also join the server and used the /rcon command to check all those settings to make sure they were in fact setup correctly and they were.

But your reply got me thinking. I didn't know your queue plugin relied on zmq in any way so I went through my config file thoroughly and realized I had the net_ip cvar in my main config file set to the servers external IP address. So I commented it out because by default it is supposed to bind to all interfaces.

This fixed the issue I was having. So it seems that it needs to bind to the localhost ip as well for the queue plugin to function properly.

Only reason I had set the net_ip to my external server IP address was because when initially setting my new dedicated server up I was having issues with not being able to see the server in the server browser list so I was just trying a few things and never went back to change it.

Anyways. Even though it wasn't one of the settings you mentioned, it did get me thinking about what I should be looking for, so thank you very much.

I very much appreciate you replying as I don't think I would have worked this out on my own and it would have driven me crazy. Your queue plugin is one of my must have plugins now.

Thank you
Craig

**Comment by Melodeiro** [comment]
Hello!
Thanks for reporting this. I will take it into attention, when will have another similar report. Some game events are working only when zmq is enabled and functioning properly. That way, a lot of minqlx plugins are rely on it. Maybe wrong net_ip just broke zmq.
