### ISSUE TITLE
Using special queue tag instead of clantag

### ISSUE THREAD

**Issue by em92** [Melodeiro/minqlx-plugins_mattiZed#6]
Hi.
Have you tried to use pq in players' configstrings instead of cn/xcn?
Found it here:
https://github.com/brugal/wolfcamql/blob/master/README-wolfcam.txt#L627

Not sure, that it will enable native qlds queue mechanism, but at least it won't use clantags to show queue.

**Comment by Melodeiro** [comment]
Hi.
I don't think, its possible, because when i trying to send some numbers in "so" and "pq" i see no changes. Probably they are displayed only when you are joining the duel server, but queue plugin is disabled in that case anyway. Did you get it work on your own?

**Comment by em92** [comment]
> Did you get it work on your own?

No. I only found info about "pq" in configstring and thought that it might be useful, if it worked.

**Comment by Melodeiro** [comment]
Okay, thanks anyway!
